// Package model defines all entity types, request/response types, and event types
// for the eiker-company-db Dapr service.
package model

import "time"

// CommonFields contains the audit and tracking fields shared by every data entity.
// All tables in this service embed these fields.
type CommonFields struct {
	// ID is the auto-increment primary key generated by the database.
	ID int64 `json:"id"`
	// IsCurrent indicates whether this record is the current valid version.
	IsCurrent bool `json:"is_current"`
	// TraceID is the distributed-tracing identifier used for log correlation.
	TraceID string `json:"trace_id,omitempty"`
	// Owner is the data-owner identifier used for permission control.
	Owner string `json:"owner,omitempty"`
	// Creater is the account that created this record.
	Creater string `json:"creater,omitempty"`
	// CreateTime is set automatically by the database on insert.
	CreateTime time.Time `json:"create_time"`
	// Updater is the account that performed the last update.
	Updater string `json:"updater,omitempty"`
	// UpdateTime is set automatically by the database on update.
	UpdateTime time.Time `json:"update_time"`
	// Remark is a free-text annotation.
	Remark string `json:"remark,omitempty"`
}
